### ISSUE TITLE
Making the command go to a new line breaks the terminal 

### ISSUE THREAD

**Issue by hax4dazy** [TechGeekGamer/JS-Terminal-Simulator#1]
Doing \n in your command breaks the terminal

readline.js:1170
            throw err;
            ^

SyntaxError: Invalid or unexpected token
    at C:\Users\Hax4dayz\Desktop\JS-Terminal-Simulator-1.0.0\app.js:55:57
    at Interface._onLine (readline.js:320:5)
    at Interface._line (readline.js:699:8)
    at Interface._ttyWrite (readline.js:1025:14)
    at ReadStream.onkeypress (readline.js:198:10)
    at ReadStream.emit (events.js:311:20)
    at emitKeys (internal/readline/utils.js:438:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1160:36)
    at ReadStream.emit (events.js:311:20)

This is the error code

**Comment by hax4dazy** [comment]
Dead project
